// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	"github.com/linabellbiu/goctl-validate/example/types/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/items",
				Handler: CreateItemHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/status",
				Handler: GetStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/test/new",
				Handler: TestNewHandler(serverCtx),
			},
		},
	)
}
