// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

import (
	"github.com/go-playground/validator/v10"
)

var validate = validator.New()

type LoginReq struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required,min=6"`
	Mobile   string `json:"mobile" validate:"mobile"`
}

type LoginResp struct {
	Token string `json:"token"`
}

func (r *LoginReq) Validate() error {
	return validate.Struct(r)
}
