// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type TestTranslationReq struct {
	Name   string `json:"name" validate:"required,min=2,max=10"`
	Age    int    `json:"age" validate:"required,gt=0,lt=150"`
	Email  string `json:"email" validate:"required,email"`
	Mobile string `json:"mobile" validate:"required,mobile"`
}

type TestTranslationResp struct {
	Message string `json:"message"`
}
