// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	"github.com/linabellbiu/goctl-validate/test/manual_test/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 测试翻译功能
				Method:  http.MethodPost,
				Path:    "/api/test",
				Handler: TestTranslationHandler(serverCtx),
			},
		},
	)
}
