// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

import (
	"github.com/go-playground/validator/v10"
)

type CommonResp struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type CreateItemReq struct {
	Name        string  `json:"name" validate:"required,min=2,max=50"`
	Description string  `json:"description" validate:"omitempty,max=200"`
	Price       float64 `json:"price" validate:"required,gt=0"`
}

type StatusReq struct {
	Id   int64  `json:"id" validate:"required,gt=0"`
	Name string `json:"name" validate:"required"`
}

type TestNewReq struct {
	NewField1 string `json:"new_field1" validate:"required,new_tag1"`
	NewField2 string `json:"new_field2" validate:"required,new_tag2"`
}

var validate = validator.New()

func (r *CreateItemReq) Validate() error {
	err := validate.Struct(r)
	return TranslateError(err)
}

func (r *StatusReq) Validate() error {
	err := validate.Struct(r)
	return TranslateError(err)
}

func (r *TestNewReq) Validate() error {
	err := validate.Struct(r)
	return TranslateError(err)
}
